#!/bin/bash

if [[ -z $1 ]]; then
  echo "Missing project name"
  exit 1
fi

project_name="$1"
group_name="ru.nsu.$1"

mvn archetype:generate -DgroupId="$group_name" -DartifactId="$project_name" -DarchetypeArtifactId=maven-archetype-quickstart -DarchetypeVersion=1.5 -DinteractiveMode=false
